Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	2	clean_indelible
	6	concat_fasta
	3	concat_summaries
	1	create_control_files
	1	create_plots
	6	run_grasp
	2	run_indelible
	6	summarise_indels
	27
Select jobs to execute...

[Sun Jan 31 18:06:27 2021]
rule create_control_files:
    output: indelible/6_control.txt
    jobid: 6
    wildcards: taxon=6

[Sun Jan 31 18:06:27 2021]
Finished job 6.
1 of 27 steps (4%) done
Select jobs to execute...

[Sun Jan 31 18:06:27 2021]
rule run_indelible:
    input: indelible/6_control.txt
    output: indelible_output/6/trees/1.nwk, indelible_output/6/6_TRUE_1.fasta, indelible_output/6/6_ANCESTRAL_1.fasta
    jobid: 5
    wildcards: taxon=6, rep=1

[Sun Jan 31 18:06:28 2021]
Finished job 5.
2 of 27 steps (7%) done
Select jobs to execute...

[Sun Jan 31 18:06:28 2021]
rule clean_indelible:
    input: indelible_output/6/trees/1.nwk, indelible_output/6/6_TRUE_1.fasta, indelible_output/6/6_ANCESTRAL_1.fasta
    output: indelible_output/6/cleaned_aln/1.fasta, indelible_output/6/cleaned_ancestors/1.fasta, indelible_output/6/concatenated/1.fasta, indelible_output/6/cleaned_N0_trees/1.nwk
    jobid: 4
    wildcards: taxon=6, rep=1

[Sun Jan 31 18:06:28 2021]
Error in rule clean_indelible:
    jobid: 4
    output: indelible_output/6/cleaned_aln/1.fasta, indelible_output/6/cleaned_ancestors/1.fasta, indelible_output/6/concatenated/1.fasta, indelible_output/6/cleaned_N0_trees/1.nwk

RuleException:
CalledProcessError in line 41 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmp90sn0l1m.clean_indelible.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 41, in __rule_clean_indelible
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-01-31T180627.212063.snakemake.log
