Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	split_trees
	1
Select jobs to execute...

[Sun Jan 24 19:36:29 2021]
rule split_trees:
    input: indelible_output/40/trees.txt
    output: indelible_output/40/40_tree_1.nwk
    jobid: 0
    wildcards: taxon=40, rep=1

[Sun Jan 24 19:36:29 2021]
Error in rule split_trees:
    jobid: 0
    output: indelible_output/40/40_tree_1.nwk

RuleException:
URLError in line 31 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
<urlopen error [Errno 2] No such file or directory: '/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/split_trees.py'>
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 31, in __rule_split_trees
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/urllib/request.py", line 517, in open
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/urllib/request.py", line 534, in _open
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/urllib/request.py", line 1477, in file_open
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/urllib/request.py", line 1516, in open_local_file
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-01-24T193629.789908.snakemake.log
