Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	4	clean_fasta
	2	create_control_files
	4	run_indelible
	11
Select jobs to execute...

[Mon Jan 25 12:03:59 2021]
rule create_control_files:
    output: indelible/40_control.txt
    jobid: 2
    wildcards: taxon=40

[Mon Jan 25 12:03:59 2021]
Finished job 2.
1 of 11 steps (9%) done
Select jobs to execute...

[Mon Jan 25 12:03:59 2021]
rule run_indelible:
    input: indelible/40_control.txt
    output: indelible_output/40/cleaned_trees/40_tree_1.nwk, indelible_output/40/40_TRUE_1.fasta
    jobid: 1
    wildcards: taxon=40, rep=1

[Mon Jan 25 12:03:59 2021]
Finished job 1.
2 of 11 steps (18%) done
Select jobs to execute...

[Mon Jan 25 12:03:59 2021]
rule clean_fasta:
    input: indelible_output/40/40_TRUE_1.fasta
    output: indelible_output/40/cleaned_aln/40_TRUE_1.fasta
    jobid: 7
    wildcards: taxon=40, rep=1

[Mon Jan 25 12:04:00 2021]
Error in rule clean_fasta:
    jobid: 7
    output: indelible_output/40/cleaned_aln/40_TRUE_1.fasta

RuleException:
CalledProcessError in line 49 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmpqduekgy9.tidy_output.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 49, in __rule_clean_fasta
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-01-25T120359.092763.snakemake.log
