Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	6	concat_fasta
	3	concat_summaries
	1	create_plots
	2	get_indelible_dict
	5	run_grasp
	6	summarise_indels
	23
Select jobs to execute...

[Mon Feb  1 09:32:36 2021]
rule run_grasp:
    input: indelible_output/6/cleaned_aln/1.fasta, indelible_output/6/cleaned_N0_trees/1.nwk
    output: grasp_results/6/BEP/1, grasp_results/6/BEP/1/GRASP_ancestors.fasta, grasp_results/6/BEP/1/tree.nwk
    jobid: 3
    wildcards: taxon=6, method=BEP, rep=1

[Mon Feb  1 09:32:36 2021]
Finished job 3.
1 of 23 steps (4%) done
Select jobs to execute...

[Mon Feb  1 09:32:36 2021]
rule concat_fasta:
    input: indelible_output/6/cleaned_aln/1.fasta, grasp_results/6/BEP/1/GRASP_ancestors.fasta
    output: grasp_results/concatenated/6/BEP/1/GRASP_ancestors.fasta
    jobid: 8
    wildcards: taxon=6, method=BEP, rep=1

[Mon Feb  1 09:32:36 2021]
Finished job 8.
2 of 23 steps (9%) done
Select jobs to execute...

[Mon Feb  1 09:32:36 2021]
rule get_indelible_dict:
    input: indelible_output/6/concatenated/2.fasta, indelible_output/6/cleaned_N0_trees/2.nwk
    output: indelible_dicts/6/leaves_2.p, indelible_dicts/6/gaps_2.p
    jobid: 16
    wildcards: taxon=6, rep=2

[Mon Feb  1 09:32:37 2021]
Error in rule get_indelible_dict:
    jobid: 16
    output: indelible_dicts/6/leaves_2.p, indelible_dicts/6/gaps_2.p

RuleException:
CalledProcessError in line 107 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmpcob501rx.get_indelible_dict.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 107, in __rule_get_indelible_dict
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-02-01T093236.125677.snakemake.log
