Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	2	clean_fastml_ml
	2	clean_fastml_parsimony
	1	clean_indelible
	1	compile_latex
	5	concat_fasta
	2	concat_fastml__ml_summaries
	2	concat_fastml_summaries
	2	concat_indelible_summaries
	8	concat_summaries
	1	generate_latex
	1	generate_output_dict
	2	get_indelible_dict
	1	run_fastml
	5	run_grasp
	2	summarise_fastml_ml_indels
	2	summarise_fastml_parsimony_indels
	2	summarise_indelible
	8	summarise_indels
	49
Select jobs to execute...

[Thu Feb  4 20:41:52 2021]
rule clean_fastml_ml:
    input: fastml_results/10/1/seq.marginal_IndelAndChars.txt, fastml_results/10/1/tree.newick.txt
    output: fastml_results_ml/10/concatenated/1/FastML_ancestors.fasta, fastml_results_ml/10/cleaned_trees/1/tree.nwk, fastml_results_ml/10/cleaned_N0_trees/1/tree.nwk
    jobid: 58
    wildcards: taxon=10, rep=1

[Thu Feb  4 20:41:53 2021]
Error in rule clean_fastml_ml:
    jobid: 58
    output: fastml_results_ml/10/concatenated/1/FastML_ancestors.fasta, fastml_results_ml/10/cleaned_trees/1/tree.nwk, fastml_results_ml/10/cleaned_N0_trees/1/tree.nwk

RuleException:
CalledProcessError in line 85 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmpy3rhukcj.clean_fastml.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 85, in __rule_clean_fastml_ml
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-02-04T204152.613775.snakemake.log
